x-seaweed: &seaweed_vols_base
  image: chrislusf/seaweedfs
  restart: always
  networks:
    - seaweed_net

services:
  seaweed_master:
    image: chrislusf/seaweedfs
    restart: always
    command: "master -volumeSizeLimitMB=${SEAWEED_VOLUME_SIZE_MB}"
    ports:
      - "9333:9333" # HTTP WebUI
      - "19333:19333"
    networks:
      - seaweed_net
    healthcheck: # Raft Leader ready?
      test: ["CMD", "curl", "-f", "http://localhost:9333/dir/status"]
      start_period: 30s
      interval: 10s
      timeout: 6s
      retries: 1

  seaweed_vol8081:
    <<: *seaweed_vols_base
    command: "volume -max=20 -master=seaweed_master:9333 -port=8081 -ip=${SEAWEED_HOST0} -ip.bind=0.0.0.0"
    ports:
      - "8081:8081"
      - "18081:18081"
    volumes:
      - ./mnt/vol8081:/data
    depends_on:
      seaweed_master:
        condition: service_healthy

  seaweed_vol8082:
    <<: *seaweed_vols_base
    command: "volume -max=10 -master=seaweed_master:9333 -port=8082 -ip=${SEAWEED_HOST0} -ip.bind=0.0.0.0"
    ports:
      - "8082:8082"
      - "18082:18082"
    volumes:
      - ./mnt/vol8082:/data
    depends_on:
      seaweed_master:
        condition: service_healthy

  seaweed_filer:
    image: chrislusf/seaweedfs
    restart: always
    command: >
      filer
      -master=seaweed_master:9333
      -ip=${SEAWEED_HOST0} -ip.bind=0.0.0.0
      -s3
    ports:
      - "8888:8888"   # WebUI
      - "8333:8333"   # S3 端口
      - "18888:18888"
    volumes:
      - ./mnt/volmeta:/data
      - ./app/seaweed_webhook/notification.toml:/etc/seaweedfs/notification.toml
    depends_on:
      seaweed_master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/"]
      interval: 10s
      timeout: 5s
      retries: 1
    networks:
      - seaweed_net

  seaweed_webhook:
    image: node:18-alpine
    restart: always
    environment:
      - NODE_ENV=production
    working_dir: /app
    volumes:
      - ./app/seaweed_webhook:/app
    command: >
      sh -c "npm install fastify && node server.js"
    ports:
      - "5000:5000"
    networks:
      - seaweed_net

  wireguard_client:
    image: lscr.io/linuxserver/wireguard
    container_name: wg_client
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - WG_IP=${WG_DEFAULT_CLIENT_IP}
    volumes:
      - ./mnt/wg_config:/config
      - ./app/wg_customized/client.ini:/_tmp/cfg
      - ./app/wg_customized/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    restart: unless-stopped
    networks:
      - seaweed_net
      - db_net

  proxy:
    image: gogost/gost
    restart: always
    network_mode: service:wireguard_client
    environment:
      - GOST_LOGGER_LEVEL=warn
    command:
      - "-L=tcp://:8333/seaweed_filer:8333"
      - "-L=tcp://:5432/db:5432"
    depends_on:
      - wireguard_client
      - db

  db:
    image: postgres:18
    ports:
      - "5432:5432"
    shm_size: 1gb
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=backend_db # create if not exists
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=512MB
      -c effective_io_concurrency=200
      -c random_page_cost=1.1
    volumes:
      - ./mnt/pg18_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d backend_db"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - db_net

  db_webui:
    image: sosedoff/pgweb
    restart: always
    ports:
      - "5433:8081"
    environment:
      - PGWEB_DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@db:5432/?sslmode=disable
      - PGWEB_AUTH_USER=${DB_USER}
      - PGWEB_AUTH_PASS=${DB_PASS}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db_net

networks:
  seaweed_net:
    driver: bridge
  db_net:
    driver: bridge
