services:

  wireguard_server:
    image: lscr.io/linuxserver/wireguard
    container_name: wg_server
    ports:
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - WG_SERVER_ID=${WG_DEFAULT_SERVER_ID}
    volumes:
      - ./mnt/wg_config:/config
      - ./templates/wg_server.ini:/_tmp/cfg
    entrypoint: >
      /bin/sh -c "
      NEW_KEY=$$(wg genkey);
      NEW_IP=10.8.$$((WG_SERVER_ID >> 8)).$$((WG_SERVER_ID & 255));
      echo \"IP: $$NEW_IP\";

      if [ ! -f /config/wg_confs/wg0.conf ]; then
        mkdir -p /config/wg_confs;
        cp /_tmp/cfg /config/wg_confs/wg0.conf;
        sed -i -e \"s|{{KEY}}|$${NEW_KEY}|g\" -e \"s|{{IP}}|$${NEW_IP}|g\" /config/wg_confs/wg0.conf;
        echo '✅ new wg0.conf.';
      else
        echo 'ℹ️ keep existing wg0.conf.';
      fi;

      exec /init
      "
    restart: unless-stopped
    networks:
      - jfs_net
      - db_net

  proxy:
    image: gogost/gost
    restart: always
    network_mode: service:wireguard_server
    environment:
      - GOST_LOGGER_LEVEL=warn
    command:
      - "-L=tcp://:8333/10.8.0.1:8333" # S3
      - "-L=tcp://:5432/10.8.0.1:5432" # DB
    depends_on:
      wireguard_server:
        condition: service_started

  redis_srv:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./mnt/redis_dump:/data
    command: >
      redis-server
      --maxmemory ${REDIS_MAX_MEMORY:-128mb}
      --maxmemory-policy noeviction
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - jfs_net

  jfs_format:
    image: juicedata/mount
    entrypoint: /bin/sh -c
    command: >
      "if juicefs status redis://redis_srv:6379/1 >/dev/null 2>&1; then
        echo '✅ JuiceFS already initialized (skipping format).';
      else
        juicefs format
        --storage s3
        --bucket http://wireguard_server:8333/jfs-bucket-1
        --access-key any --secret-key any
        --capacity ${JFS_CAPACITY_GB}
        redis://redis_srv:6379/1
        ${JFS_NAME};
      fi"
    depends_on:
      redis_srv:
        condition: service_healthy
      proxy:
        condition: service_started
    networks:
      - jfs_net

  jfs_mount:
    image: juicedata/mount
    restart: always
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./mnt/jfs_cache:/var/jfs_cache
      - ./mnt/jfs:/mnt/jfs:shared
    command: >
      juicefs mount
      --cache-dir /var/jfs_cache
      --buffer-size ${JFS_BUFFER_SIZE_MB}
      --cache-size ${JFS_CACHE_SIZE_MB}
      --free-space-ratio 0.1
      --get-timeout 10
      --put-timeout 10
      --io-retries 2
      redis://redis_srv:6379/1
      /mnt/jfs
    depends_on:
      jfs_format:
        condition: service_completed_successfully
      proxy:
        condition: service_started
    networks:
      - jfs_net

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8001:8001
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@wireguard_server:5432/pg18_db
      - PYTHONUNBUFFERED=1
    volumes:
      - ./mnt/backend:/app
    depends_on:
      proxy:
        condition: service_started
    networks:
      - db_net

networks:
  jfs_net:
    driver: bridge

  db_net:
    driver: bridge
